prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    ruleSelector: {}
    ruleNamespaceSelector: {}

grafana:
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL

alertmanager:
  enabled: true
