spring.application.name=technical-interview-demo
spring.datasource.url=jdbc:h2:mem:demo-db
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.generate_statistics=true
management.tracing.sampling.probability=1.0
spring.output.ansi.enabled=DETECT
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false
#logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr([rid=%X{rid:-} trace=%X{traceId:-} span=%X{spanId:-}]){yellow} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
