# IntelliJ HTTP Client examples for technical-interview-demo

@baseUrl = http://localhost:8080

### TechnicalOverviewController - supported root technical overview
GET {{baseUrl}}/
Accept: application/json

### TechnicalOverviewController - supported hello endpoint
GET {{baseUrl}}/hello
Accept: text/plain
