### GET hello world
GET http://localhost:8080/hello

### list books
GET http://localhost:8080/api/books

### add book
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "isbn": "978-0743273565",
  "publicationYear": 1925
}

### get book by id
GET http://localhost:8080/api/books/3

### update book
PUT http://localhost:8080/api/books/3
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "publicationYear": 1926
}

### delete book
DELETE http://localhost:8080/api/books/3

### actuator info
GET http://localhost:8080/actuator/info

### actuator health
GET http://localhost:8080/actuator/health