create table books (
    id bigint generated by default as identity primary key,
    version bigint not null,
    title varchar(255) not null,
    author varchar(255) not null,
    isbn varchar(255) not null,
    publication_year integer not null,
    constraint uk_books_isbn unique (isbn)
);
