create table localization_messages
(
    id           bigint generated by default as identity primary key,
    message_key  varchar(150)  not null,
    language     varchar(8)    not null,
    message_text varchar(2000) not null,
    description  varchar(1000),
    created_at   timestamp     not null,
    updated_at   timestamp     not null,
    constraint uk_localization_messages_message_key_language unique (message_key, language)
);

create index idx_localization_messages_language on localization_messages (language);
