create table categories (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    constraint uk_categories_name unique (name)
);

create table book_categories (
    book_id bigint not null,
    category_id bigint not null,
    constraint pk_book_categories primary key (book_id, category_id),
    constraint fk_book_categories_book foreign key (book_id) references books (id),
    constraint fk_book_categories_category foreign key (category_id) references categories (id)
);
