create table users (
    id bigint generated by default as identity primary key,
    provider varchar(50) not null,
    external_login varchar(100) not null,
    display_name varchar(255),
    email varchar(255),
    preferred_language varchar(8),
    last_login_at timestamp not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_users_provider_external_login unique (provider, external_login)
);

create table user_roles (
    user_id bigint not null,
    role varchar(50) not null,
    constraint pk_user_roles primary key (user_id, role),
    constraint fk_user_roles_user foreign key (user_id) references users (id)
);

create index idx_users_provider_external_login on users (provider, external_login);
