create table audit_logs (
    id bigint generated by default as identity primary key,
    target_type varchar(50) not null,
    target_id bigint not null,
    action varchar(50) not null,
    actor_user_id bigint,
    actor_login varchar(100),
    summary varchar(1000) not null,
    created_at timestamp not null,
    constraint fk_audit_logs_actor_user foreign key (actor_user_id) references users (id)
);

create index idx_audit_logs_target on audit_logs (target_type, target_id);
create index idx_audit_logs_actor on audit_logs (actor_user_id);
