apiVersion: v1
kind: Secret
metadata:
  name: technical-interview-demo-secrets
  namespace: technical-interview-demo
  labels:
    app.kubernetes.io/name: technical-interview-demo
    app.kubernetes.io/component: app
type: Opaque
stringData:
  DATABASE_PASSWORD: change-me
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  ADMIN_LOGINS: ""
