apiVersion: v1
kind: Service
metadata:
  name: technical-interview-demo
  namespace: technical-interview-demo
  labels:
    app.kubernetes.io/name: technical-interview-demo
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: technical-interview-demo
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: http
